# Generated by Django 5.2.9 on 2026-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
