# Generated by Django 5.2.9 on 2026-01-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventary', '0002_remove_product_name_product_gst_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
